name: location_box
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  #Core
  equatable: ^2.0.5
  google_maps_flutter: ^2.5.0
  get_it: ^7.6.4
  permission_handler: ^11.1.0

  # utils
  google_fonts: ^6.1.0
  easy_localization: ^3.0.3
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  kartal: ^3.5.0
  lottie: ^2.7.0
  uuid: ^4.2.2
  intl: ^0.18.1
  logger: ^2.0.2+1
  image_picker: ^1.0.5

  # State Management
  flutter_bloc: ^8.1.3

  # Navigation
  auto_route: ^7.8.4

  # location
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Annotations
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_gen_runner: ^5.3.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/lottie/
